### ISSUE TITLE
ImportError: cannot import name 'PagedAttentionWithRoPE'

### ISSUE THREAD

**Issue by Baekpica** [mobiusml/hqq#6]
First of all, thank you for your wonderful work!

I would like to report a minor issue with library import.
Due to a refactoring of the vLLM library, HQQ's vllm engine is not working as shown below.

The latest version of vLLM is 0.2.6, and the HQQ's vllm engine only works with vllm <= 0.2.2.

I hope this helps you.

![스크린샷 2023-12-22 오후 4 56 28](https://github.com/mobiusml/hqq/assets/35071468/b6d41071-b2df-4f13-bfd3-91ad3a012855)

**Comment by mobicham** [comment]
Thanks @Baekpica ! I added that in the Readme for now, we will have to rewrite the llama.py file to account for the refactoring.
